### ISSUE TITLE
Update to .Net 6

### ISSUE THREAD

**Issue by anubisatari** [Breeze/northwind-demo#31]
When will you be updating to .Net 6?

**Comment by jtraband** [comment]
All of the Breeze libraries have been updated to .NET 6.  Only the demo's have not yet been migrated. But there are will be no code changes required to those, AFAIK.

**Comment by steveschmitt** [comment]
Soon.  Within a month.  [Breeze](https://www.nuget.org/packages/Breeze.Persistence.EFCore/) has already been updated for .NET 6, but I still need to update this demo.

The code will change very little, if at all.

**Comment by anubisatari** [comment]
I would like to thank you for your time on this project, it's nice moving from JavaScript to Angular and having Breeze to manage my data. Nice and familiar. I don't want to open another issue, but I would like to ask a couple more questions.

1) .net 6 Core API project no longer has Startup.cs, I know we can still use it, but would you please give a good example of a .net 6 Program.cs? I have one working, but I always feel like it's not entirely correct.

2) In the EntityManagerProvider, I have an example for using a JWT if anybody needs that snippet:
AjaxFetchAdapter.register().requestInterceptor = ((req) => {
			req.config.headers.Authorization = `Bearer ${localStorage.getItem('token')}`;
		}) as any;
If it can be improved, please let me know.

3) Are there any plans for moving away from Promises for Angular to Observables for executeQuery?

Again, thank you very much for updating Breeze for Angular and .net Core.

**Comment by steveschmitt** [comment]
Regarding question 3: Breeze will continue to use Promises because they are an ECMAScript standard and do not depend on any library.  

However, @marcelgood has created UnitOfWork and Repository wrappers that expose Breeze concepts as Observables.  We are using these in our Angular projects.  Take a look at the [TempHire](https://github.com/Breeze/temphire.angular/tree/master/TempHire/app/core/services) sample repo.

**Comment by marcelgood** [comment]
1. We don't have a .NET 6 example yet, but probably we'll create one at some point.
2. Effectively, yes, token should be injected via an HTTP interceptor. The above is one way or you can create a standalone interceptor and inject it via DI. There are split opinions on storing your token in local storage, though, due to security concerns. Especially the refresh token is a concern and there are approaches to not requiring one. 
3. As said above, we don't have plans to depend on RxJS directly with Breeze, but potentially a library that can be run on top that exposes Breeze concepts as Observables. As @steveschmitt said, we are using a UoW and Repository abstraction layer on top of Breeze. TempHire doesn't have the latest, but our current implementation is a 100% Observables at the UoW and Repository layer. All the Breeze events and Promise operations are turned into Observables. Below is an example of the latest Repository interface and then it's very easy to wrap executeQuery inside of it and return an Observable. 

```
export interface Repository<T extends Entity> {
  withId(key: any | any[], checkLocalCacheFirst?: boolean): Observable<T>;
  fetch(queryAction?: (queryBuilder: QueryBuilder<T>) => void, options?: FetchOptions): Observable<T[]>;
  fetch<TResult, TParams>(resourceName: string, params?: TParams): Observable<TResult[]>;
  fetchPage(initialPageSize: number, queryAction?: (queryBuilder: QueryBuilder<T>) => void): Paginator<T>;
  count(queryAction?: (queryBuilder: QueryBuilder<T>) => void): Observable<number>;
}
```

```
  protected executeQuery(
    query: EntityQuery,
    options?: {
      fetchStrategy?: FetchStrategy;
    }
  ): Observable<T[]>;
  protected executeQuery(
    query: EntityQuery,
    options?: {
      fetchStrategy?: FetchStrategy;
      observe: 'response';
    }
  ): Observable<QueryResult>;
  protected executeQuery(
    query: EntityQuery,
    options?: {
      fetchStrategy?: FetchStrategy;
      observe?: string;
    }
  ): Observable<T[]> | Observable<QueryResult> {
    options = options || {};
    const q = query.using(options.fetchStrategy || this.defaultFetchStrategy);

    if (options.observe === 'response') {
      return defer(() => this.helper.busyService.busy$('Loading data...', from(this.manager.executeQuery(q))));
    }

    return defer(() =>
      this.helper.busyService
        .busy$('Loading data...', from(this.manager.executeQuery(q)))
        .pipe(map((response) => response.results as T[]))
    );
  }
```

**Comment by anubisatari** [comment]
Thanks for the feedback. You have been more than awesome answering my questions.
Closing the ticket with this post.
